name: web-map-feature-services-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - pip
  - cartopy
  - pip:
      - sphinx-pythia-theme
      - jupyter_bokeh
      - requests
      - geoviews
      - panel
      - geopandas
      - hvplot