name: web-map-feature-services-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - jupyterlab-myst
  - jupyter_server
  - cartopy
  - jupyter_bokeh
  - requests
  - geoviews
  - panel
  - geopandas
  - hvplot
  - owslib
  - mystmd
