name: web-map-feature-services-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - pip
  - cartopy
  - jupyter_bokeh
  - requests
  - geoviews
  - panel
  - geopandas
  - hvplot
  - owslib
  - sphinx-pythia-theme
  - mystmd
